# Docker Compose file for Isaac ROS 2 Control
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a specific service by name:
#   docker compose up <name>
#
# To open an interactive shell to a running container:
# (You can tab complete to get the container name)
#   docker exec -it <container_name> bash
services:
  demo_isaac_zimmer:
    build:
      context: ../
      dockerfile: Docker/.docker/Dockerfile
      args:
        USE_LOCAL: "true"
    image: demo_isaac_zimmer:latest
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    command: ros2 launch moveit_config isaac_demo.launch.py ros2_control_hardware_type:=isaac

  demo_isaac:
    build:
      context: ../
      dockerfile: Docker/.docker/Dockerfile
      args:
        USE_LOCAL: "false"
    image: demo_isaac:latest
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    command: ros2 launch moveit_config isaac_demo.launch.py ros2_control_hardware_type:=isaac
